### ISSUE TITLE
Update Hackage version

### ISSUE THREAD

**Issue by guaraqe** [gtk2hs/gtkglext#2]
Since this version build well with the lastest GHC version, is it possible to update the Hackage version? It would make building things depending on GtkGlExt with cabal easier.

**Comment by maoe** [comment]
+1

**Comment by Tosainu** [comment]
+1

**Comment by olmayan** [comment]
+1

**Comment by maoe** [comment]
What is blocking a new release? Is there anything I can help?

**Comment by guaraqe** [comment]
@hamishmack was the last person to commit to the repo, maybe he can help?

**Comment by hamishmack** [comment]
Updated
